# Generated by Django 2.2 on 2020-01-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creater', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('process', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(verbose_name='prepared date')),
            ],
        ),
    ]
