# Generated by Django 2.2 on 2020-01-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_recipe_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='creater',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
